import Head from "next/head";

const Home = () => {
  const downloadImage = async (a: HTMLAnchorElement, index: number) => {
    const blob = await fetch(
      "https://res.cloudinary.com/beleza-na-web/image/upload/f_auto,fl_progressive,q_auto:low,w_400/v1/banner/2022_11_21_19_10_07_2/7446d0d8-9086-42c4-8417-b1676ab8ee3a-3-minis-39-bn-mobile2.jpg"
    ).then((res) => res.blob());
    a.href = URL.createObjectURL(blob);
    a.download = `myImage-${index}.png`;
    a.click();
  };

  const downloadImages = async () => {
    const a = document.createElement("a");
    a.style.display = "none";
    document.body.appendChild(a);
    for (let i = 0; i < 3; i++) {
      downloadImage(a, i);
    }
    document.body.removeChild(a);
  };

  return (
    <div className="flex flex-col justify-center items-center gap-2 w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={downloadImages} className="bg-black text-white px-2">
        download
      </button>
    </div>
  );
};

export default Home;
