import Head from "next/head";
import { ChangeEvent, useState } from "react";

declare global {
  interface Window {
    Native: any;
  }
}

const Home = () => {
  const delay = (ms: number) =>
    new Promise((resolve) => setTimeout(resolve, ms));

  const download = async (url: string, filename: string) => {
    const a = document.createElement("a");
    a.style.display = "none";
    document.body.appendChild(a);
    a.href = url;
    a.download = filename;
    a.click();

    await delay(100);
    document.body.removeChild(a);
  };

  const downloadImagesWeb = async (images: string[]) => {
    images.forEach(async (image) => {
      const [filename, extension] = image.split(".");
      const finalFilename = `${filename}_${new Date().toLocaleDateString(
        "pt-BR"
      )}_${new Date().toLocaleTimeString("pt-BR", {
        hour: "numeric",
        minute: "numeric",
        second: "numeric",
        fractionalSecondDigits: 3,
      })}.${extension}`;

      await download(`${window.location.href}${image}`, finalFilename);

      setImagesToDownload((checkedImages) =>
        checkedImages.filter((checkedImage) => image !== checkedImage)
      );
    });
  };

  const downloadImages = async () => {
    if (window.Native) {
      imagesToDownload.forEach((image) => {
        window.Native.downloadFile(`${window.location.href}${image}`);
      });
      return;
    }
    downloadImagesWeb(imagesToDownload);
  };

  const [imagesToDownload, setImagesToDownload] = useState<string[]>([]);

  const handleChangeCheckbox =
    (image: string) => (event: ChangeEvent<HTMLInputElement>) => {
      if (event.target.checked) {
        return setImagesToDownload([...imagesToDownload, image]);
      }
      setImagesToDownload(imagesToDownload.filter((img) => img !== image));
    };

  return (
    <div className="flex flex-col justify-center items-center gap-2 w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-4">
        {[1, 376, 523].map((id) => (
          <label key={id} className="flex flex-col gap-4">
            <img
              src={`/${id}-200x300.jpg`}
              alt="download image"
              className="max-w-[120px] max-h-[120px] border border-solid border-black"
            />
            <input
              type="checkbox"
              className="self-center"
              onChange={handleChangeCheckbox(`${id}-200x300.jpg`)}
              checked={imagesToDownload.includes(`${id}-200x300.jpg`)}
            />
          </label>
        ))}
      </div>
      <button
        onClick={downloadImages}
        className="p-2 bg-black text-white rounded-md"
      >
        download
      </button>
      <hr className="h-px my-8 bg-gray-700 border-0" />
      <div className="flex gap-4">
        {[1, 376, 523].map((id) => (
          <a key={id} href={`/${id}-200x300.jpg`} download>
            <img
              src={`/${id}-200x300.jpg`}
              alt="download image"
              className="max-w-[120px] max-h-[120px] border border-solid border-black"
            />
          </a>
        ))}
      </div>
    </div>
  );
};

export default Home;
