import Head from "next/head";
import { ChangeEvent, useState } from "react";

import multiDownload from "multi-download";

declare global {
  interface Window {
    Native: any;
  }
}

const Home = () => {
  const downloadImages = async () => {
    if (window.Native) {
      imagesToDownload.forEach((image) => {
        window.Native.downloadFile(`${window.location.href}${image}`);
      });
      return;
    }
    await multiDownload(imagesToDownload);
  };

  const [imagesToDownload, setImagesToDownload] = useState<string[]>([]);

  const handleChangeCheckbox =
    (image: string) => (event: ChangeEvent<HTMLInputElement>) => {
      if (event.target.checked) {
        return setImagesToDownload([...imagesToDownload, image]);
      }
      setImagesToDownload(imagesToDownload.filter((img) => img !== image));
    };

  return (
    <div className="flex flex-col justify-center items-center gap-2 w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-4">
        {[1, 376, 523].map((id) => (
          <label key={id} className="flex flex-col gap-4">
            <img
              src={`/${id}-200x300.jpg`}
              alt="download image"
              className="max-w-[120px] max-h-[120px] border border-solid border-black"
            />
            <input
              type="checkbox"
              className="self-center"
              onChange={handleChangeCheckbox(`${id}-200x300.jpg`)}
              checked={imagesToDownload.includes(`${id}-200x300.jpg`)}
            />
          </label>
        ))}
      </div>
      <button
        onClick={downloadImages}
        className="p-2 bg-black text-white rounded-md"
      >
        downloadd
      </button>
    </div>
  );
};

export default Home;
